# Generated by Django 3.1.2 on 2020-11-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201105_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='year',
            field=models.CharField(default='20', max_length=4),
        ),
    ]
