# Generated by Django 3.1.2 on 2020-11-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured',
        ),
    ]
