# Generated by Django 3.1.2 on 2020-11-27 09:55

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogpost_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=markdownx.models.MarkdownxField(default='Markdown形式で書いてください。', verbose_name='本文'),
        ),
    ]
