# Generated by Django 3.1.2 on 2020-11-27 10:15

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201127_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='text',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=markdownx.models.MarkdownxField(default='', verbose_name='Content'),
        ),
    ]
