# Generated by Django 3.1.2 on 2020-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201127_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('python', 'Python'), ('django', 'Django'), ('go', 'Go'), ('react', 'React'), ('javascript', 'Javascript'), ('git', 'Git'), ('aws', 'Aws'), ('book', 'Book')], default='python', max_length=50),
        ),
    ]
